clc;
close all;
n0=-10:10;
x=(n0>=0)==1;
subplot(3,1,1);
stem(n0,x);
title('Unit Step Function');
xlabel('Time');
ylabel('Amplitude');
y=(n0==0)==1;
subplot(3,1,2);
stem(n0,y);
title('Unit Impulse Function');
xlabel('Time');
ylabel('Amplitude');
z=((n0>=0)==1).*n0;
subplot(3,1,3);
stem(n0,z);
title('Ramp Function');
xlabel('Time');
ylabel('Amplitude');