clc;
close all;
N=input('Enter the length of the sequence ');
xk=input('Enter the sequence: ');
n=0:N-1;
k=0:N-1;
wN=exp((1i*2*pi)/N);
nk=n'*k;
wNnk=wN.^nk;
xn=(xk*wNnk)/N;
disp('xn-->>');
disp(xn);
mag=abs(xn);
subplot(2,1,1);
stem(n,mag);
grid on;
title('IDFT sequence of xk');
xlabel('n-->>');
ylabel('Magnitude(x(k))');
phase=angle(xn);
subplot(2,1,2);
stem(n,phase);
grid on;
title('Phase of the Fourier Transform');
xlabel('n-->');
ylabel('Phase(x(n))');
