clc;
close all;
n=-10:10;
x=(n>=0)==1;
subplot(3,1,1);
stem(n,x);
title("UnitStepFunction");
xlabel("Discrete Time");
ylabel("Amplitude");
y=(n==0)==1;
subplot(3,1,2);
stem(n,y);
title("UnitImpulseFunction");
xlabel("Discrete Time");
ylabel("Amplitude");
z=((n>=0)==1).*n;
subplot(3,1,3);
stem(n,z);
title("UnitRampFunction");
xlabel("Discrete Time");
ylabel("Amplitude");