clc;
close all;
t=0:0.0001:.25;
fm=25;
m=cos(2*pi*f1*t);
subplot(3,1,1);
plot(t,m);
title('Message Signal');
xlabel('Time');
ylabel('Amplitude');
fc=400;
c=sin(2*pi*fc*t);
subplot(3,1,2);
plot(t,c);
title('Carrier Signal');
xlabel('Time');
ylabel('Amplitude');
mf=10;
s1=sin(2*pi*fc*t+mf.*(sin(2*pi*fm*t)));
subplot(3,1,3);
plot(t,s1);
title('Modulated signal');
xlabel('Time');
ylabel('Amplitude');
